# Generated by Django 5.0.6 on 2024-11-26 02:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место привычки')),
                ('time', models.TimeField(blank=True, default=datetime.time(12, 0), null=True, verbose_name='время когда необходимо выполнять')),
                ('useful_bonus', models.CharField(blank=True, max_length=35, null=True, verbose_name='признак полезной привычки')),
                ('periodicity', models.IntegerField(default=datetime.timedelta(days=1), verbose_name='перодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.TimeField(default=datetime.timedelta(seconds=90), verbose_name='время на выполнение')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='telegram id')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
