# Generated by Django 5.0.6 on 2024-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, verbose_name='перодичность в днях'),
        ),
    ]
