# Generated by Django 5.0.6 on 2024-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.TimeField(default='PT90S', verbose_name='время на выполнение'),
        ),
    ]
