# Generated by Django 5.0.6 on 2024-11-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=100, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(max_length=100, verbose_name='вознаграждение'),
        ),
    ]
