# Generated by Django 5.0.6 on 2024-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.CharField(blank=True, default='00:01:30', null=True, verbose_name='время на выполнение'),
        ),
    ]
