# Generated by Django 5.0.6 on 2024-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]
