# Generated by Django 5.0.6 on 2024-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_habit_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='useful_bonus',
        ),
        migrations.AddField(
            model_name='habit',
            name='pleasantly',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='признак полезной привычки'),
        ),
    ]
