# Generated by Django 5.0.6 on 2024-11-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_remove_habit_useful_bonus_habit_pleasantly'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='признак публичности'),
        ),
    ]
