# Generated by Django 5.0.6 on 2024-11-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_alter_habit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая дата выполнения'),
        ),
    ]
